export const todoTypes = {
  GET_TODO_REQUEST: "GET_TODO_REQUEST",
  GET_TODO_FINISH: "GET_TODO_FINISH",
  GET_TODO_FAIL: "GET_TODO_FAIL",
  
  ADD_TODO_REQUEST: "ADD_TODO_REQUEST",
  ADD_TODO_FINISH: "ADD_TODO_FINISH",
  ADD_TODO_FAIL: "ADD_TODO_FAIL",

  EDIT_TODO_REQUEST: "EDIT_TODO_REQUEST",
  EDIT_TODO_FINISH: "EDIT_TODO_FINISH",
  EDIT_TODO_FAIL: "EDIT_TODO_FAIL",

  DELETE_TODO_REQUEST: "DELETE_TODO_REQUEST",
  DELETE_TODO_FINISH: "DELETE_TODO_FINISH",
  DELETE_TODO_FAIL: "DELETE_TODO_FAIL",

  COMPLETE_TODO_REQUEST: "COMPLETE_TODO_REQUEST",
  COMPLETE_TODO_FINISH: "COMPLETE_TODO_FINISH",
  COMPLETE_TODO_FAIL: "COMPLETE_TODO_FAIL",
};
